

services:
  web:
    build: .
    container_name: monitor_web
    command: >
      /entrypoint.sh
      gunicorn django_celery_rabbitmq_docker.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
    env_file: .env
    depends_on:
        - postgres
        - rabbitmq
        - redis
    volumes:
      - .:/app
    networks:
        - "default"
        - "proxy"
    environment:
        - VIRTUAL_HOST=heyartem.ru,www.heyartem.ru      # читает nginx-proxy отвечает за Маршрутизация HTTP
        - LETSENCRYPT_HOST=heyartem.ru,www.heyartem.ru      # читает acme-companion, отвеч для каких доменов выпускать сертификат
        - LETSENCRYPT_EMAIL=artem_white@mail.ru     # читает acme-companion, отвечает за Контакт для LE (уведомление о SSL)
        - VIRTUAL_PORT=8000
    restart: unless-stopped

  worker:
    build: .
    container_name: monitor_worker
    command: >
      /entrypoint.sh
      celery -A django_celery_rabbitmq_docker worker -l info
    env_file: .env
    depends_on:
        - postgres
        - rabbitmq
        - redis
    volumes:
      - .:/app
    restart: unless-stopped

  beat:
    build: .
    container_name: monitor_beat
    command: >
      /entrypoint.sh
      celery -A django_celery_rabbitmq_docker beat -l info
    env_file: .env
    depends_on:
        - postgres
        - rabbitmq
        - redis
    volumes:
      - .:/app
    restart: unless-stopped

  flower:
    image: mher/flower:1.2
    container_name: monitor_flower
    command: >
      celery --broker=${CELERY_BROKER_URL} flower
      --port=5555
    env_file: .env
    ports:
      - "5555:5555"
    depends_on:
        - rabbitmq
        - redis
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: monitor_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: monitor_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Mgmt UI
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: monitor_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: monitor_prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"       # UI: http://IP:9090
    restart: unless-stopped

  redis_exporter:
    image: oliver006/redis_exporter:v1.67.0
    container_name: monitor_redis_exporter
    environment:
      - REDIS_ADDR=redis:6379
    restart: unless-stopped

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: monitor_postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: monitor_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.7
    container_name: monitor_grafana
    ports:
      - "3000:3000"             # Web UI Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=change_me_please
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    # (не обязательно) если хочешь выдавать Grafana по домену через nginx-proxy:
    # networks:
    #   - proxy
    # environment:
    #   - VIRTUAL_HOST=grafana.heyartem.ru
    #   - LETSENCRYPT_HOST=grafana.heyartem.ru
    #   - VIRTUAL_PORT=3000



volumes:
  pgdata:
  rabbitmqdata:
  redisdata:
  grafana_data:

networks:
  proxy:
    external: true
